[phases.setup]
nixPkgs = ["...", "deno", "ffmpeg"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "mkdir -p downloads"
]

[start]
cmd = "python app.py"
